### ISSUE TITLE
Add support for Cold War Assault / Armed Assault

### ISSUE THREAD

**Issue by Keith94** [rex706/ArmA-FOV-Changer#1]
I noticed that Arma: Cold War Assault and Arma: Armed Assault may need FOV fixes much in the same way as Arma 2 and 3... can they be supported by your tool at some point?

**Comment by rex706** [comment]
You got it homie.

**Comment by Keith94** [comment]
Thanks! So, to clarify... does this add proper widescreen support for Cold War Assault?

[WSGF](http://www.wsgf.org/dr/arma-cold-war-assault/en) says that various `ui` settings should be adjusted as well (`uiTopLeftX`, etc.).

Also for Armed Assault, the FOV settings are stored in `*.ArmAProfile`, I don't know if that's supported here.

**Comment by rex706** [comment]
You're right about the `ui` settings and I have fixed that for the next update according to [this pdf](http://ofp-faguss.com/files/ofp_aspect_ratio.pdf) I found from your link.

I don't own Armed Assault unfortunately. Could you comment with the `default profile file path` and if the profile name is in the file name or the parent directory? I think it's in `Documents\ArmA` and that the name is in the file name. Does Armed Assault also need support for tweaking the `ui` settings?

**Comment by Keith94** [comment]
Ahh, that's great you were able to fix it! It's much simpler to tweak now.

For Armed Assault, according to [PCGW](http://pcgamingwiki.com/wiki/Arma:_Armed_Assault) the configuration file is `\Documents\ArmA\<user-id>.ArmAProfile` which is similar structure to Arma 2 and 3 I believe. The UI does not appear to be stretched this time (yay!). As always, I will update PCGW page once it's supported.

**Comment by rex706** [comment]
I had no idea PCGW had that kind of information! Definitely remembering that for the future.

I think I got it all working and pushed the release. Let me know if you find anything else that could be changed or added.

**Comment by Keith94** [comment]
Cool! So far, I tried the newest version with Cold War Assault, but upon hitting "save" the app crashes... this is the default config file that I used it with: http://pastebin.com/73kG1n39

**Comment by rex706** [comment]
Oops! I tried cheating the line read and that got me in trouble. Give the newest release another go.

**Comment by Keith94** [comment]
That works, no more crashes.

I noticed the aspect ratio detection for custom resolutions may not always be working... for example 1680x1050 is not detected as 16:10, 2560x1080 and 3440x1440 are not detected as 21:9, etc..

**Comment by rex706** [comment]
I (hopefully) fixed the aspect ratio math. It should work correctly for at least the supported Cold War Assault pdf ratios that matter.

**Comment by Keith94** [comment]
Yes, it seems to be working a lot better.

I was going to mention that the upper limit of the slider should probably be increased to accommodate the wider aspect ratios. For example (based on the pdf) 7680x1080 (`63:9`) should have `fovLeft` set to `5.333333`, but your tool only goes as high as `3.41` which is most likely not enough to be playable.

And/or you could have an "auto fov" setting that ignores the slider and just uses all values from the pdf?

**Comment by rex706** [comment]
I updated the slider max value and made the window appear overall less confusing. I also did what you suggested and put Cold War Assault into auto mode and load all of the respective values from the pdf. 

I very much appreciate all of your feedback!

**Comment by Keith94** [comment]
No problem, and thanks for listening to all my requests too. :)

My original idea for the first game was to have all those "special" values set up automatically (for those who didn't want to bother with doing it manually), but also _keep_ the FOV slider available (for those who wanted to have a wider-than-default FOV).

I'm sorry if this adds too much to the "complexity" of the app, but is there any way to restore the slider functionality back in as well? It shouldn't be forgotten imo.

**Comment by rex706** [comment]
Added a toggle for auto mode!

I was confused and thought changing the fov would mean the ui settings would not longer be correct.

**Comment by Keith94** [comment]
Ahh nice job, it works just like it should now.

I don't suppose it makes sense to add a UI element for typing in the desired FOV as well as numerical up/down buttons for easier specification of values? It could work for all the games, similar to this:

![2016-12-13_11-02-13](https://cloud.githubusercontent.com/assets/5490615/21154585/c6351e3c-c123-11e6-8115-67babea0e6b5.png)

**Comment by rex706** [comment]
Added something very similar to the H5Tweak. Let me know what you think!

Off topic, but I also edited the H5Tweak source a little to save my settings to a file so I don't have to keep entering them every time I launch the game. I also set it up to open the Halo Hub (where you press "play now") and wait for the game to be ready (about the main menu) to automatically input my saved values. I passed it around to a few friends who found it useful so if you have any interest in checking it out, I will attach it. Hopefully 343 will update the game with full functionality soon!

[H5Tweak rex edition.zip](https://github.com/rex706/ArmA-FOV-Changer/files/659241/H5Tweak.rex.edition.zip)

**Comment by Keith94** [comment]
>Added something very similar to the H5Tweak. Let me know what you think!

I like it, it's useful to have. One issue with it I'd like to point out, if you start typing a value that is outside the slider range (for example start typing "12" because you want "120") then it will delete your custom value and change to the lowest "65". I'm assuming there's a way to fix that, though.

>Off topic, but I also edited the H5Tweak source a little to save my settings to a file so I don't have to keep entering them every time I launch the game.

This is interesting, thanks for posting it. I wonder since H5Tweak is officially "deprecated", it might not work anymore with later updates. Have you looked at all into using or modifying another tool known as [Bleam](https://github.com/no1dead/Bleam)?

**Comment by rex706** [comment]
Oops you're totally right. I tried to plan for problems and that ended up causing some. Try out the latest release.

I have not heard of Bleam until just now. Definitely checking it out and I'll see what I can do.

**Comment by Keith94** [comment]
Okay, latest release fixed all problems for me. :) Let me know if Bleam is any better if you'd like.
