### ISSUE TITLE
Host releases on GitHub

### ISSUE THREAD

**Issue by Keith94** [rex706/ArmA-FOV-Changer#2]
Please upload compiled releases to GitHub, and update readme with the new link. Thank you. :)

**Comment by rex706** [comment]
The link has already been updated in the readme! There's a download link directly below the images. Or you can alternatively use https://drive.google.com/open?id=0B2byNRcR0k4vVm90NFB0azJMaVk

Do you mean you want me to include release builds in the repository? Or host the files directly somewhere else on GitHub?

**Comment by Keith94** [comment]
I meant you should upload the newest version to [releases](https://github.com/rex706/ArmA-FOV-Changer/releases) page, sorry for the confusion there.

**Comment by rex706** [comment]
Oh! Just updated the page. Thanks for the tip 8)

**Comment by Keith94** [comment]
Great, thanks for adding it!
